### ISSUE TITLE
App not registered when using reg-co-fx!

### ISSUE THREAD

**Issue by zendevil** [akiroz/re-frame-storage#12]
I'm using the library like so, copying directly from the README.

```
;; both :fx and :cofx keys are optional, they will not be registered if unspecified.
(reg-co-fx! :my-app         ;; local storage key
            {:fx :store     ;; re-frame fx ID
             :cofx :store}) ;; re-frame cofx ID


```

But I'm getting the following error when I put this snippet:
<img width="480" alt="Screen Shot 2021-01-07 at 3 40 29 PM" src="https://user-images.githubusercontent.com/30054030/103881019-e42d7900-50ff-11eb-88c7-26ac917497af.png">

How to fix this error?

**Comment by akiroz** [comment]
Hello, thanks for the issue.
There doesn't seem to be enough information here to tackle this problem, can you try using JS' local storage directly or the underlying library [storage-atom](https://github.com/alandipert/storage-atom) to see if there are any issue?

**Comment by zendevil** [comment]
How to use the js storage directly?

**Comment by akiroz** [comment]
This should get you started: https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage
