### ISSUE TITLE
add missing dep "org.clojure/spec.alpha"

### ISSUE THREAD

**Issue by jtkDvlp** [akiroz/re-frame-storage#2]
Please add missing dependence "org.clojure/spec.alpha". Thx

**Comment by jtkDvlp** [comment]
re-frame dep is also missing

**Comment by jtkDvlp** [comment]
Sry, Of course cljs/spec/alpha is contained in cljs itself (I got an old cljs version).

**Comment by akiroz** [comment]
@jtkDvlp Sorry about the 1-year-late reply, I never got a notification from GitHub :(

re-frame is missing because I expected projects using this to have its own version on it (kinda like the js peerDependency concept).

I've migrated to `cljs.spec.alpha` around June 2017, closing this now.
