### ISSUE TITLE
Persist entire db with interceptor

### ISSUE THREAD

**Issue by PabloReszczynski** [akiroz/re-frame-storage#3]
In some cases, one would like to persist the entire database in local storage with the interceptor.
For the moment my solution is to create an interceptor for every key of my db.

**Comment by akiroz** [comment]
@PabloReszczynski Sorry about the late reply, I was never notified by GitHub...

Do you have a specific use-case where putting everything under a single persisted key won't work?

And do you have an API in mind for this feature? Maybe passing a special name-spaced keyword as the persisted key like `:akiroz.re-frame.storage/entire-db`?
