### ISSUE TITLE
Unsetting value

### ISSUE THREAD

**Issue by heyarne** [akiroz/re-frame-storage#4]
Is there a way to unset a previously registered value? My use case is saving credentials until a user logs out. Just `dissoc`ing it doesn't work because the library seems to check for non-nil values. Why is that?

**Comment by akiroz** [comment]
@heyarne Sorry about the late reply, I was never notified by GitHub.

Using `dissoc` won't work because the key itself is missing, but you can `assoc` nil to your persisted key.

I'm closing this for now.
